// Generated by Claude Opus 4.6

export type ServiceListItemT = {
	id: string;
	name: string;
	slug: string;
	domain: string | null;
	verified: boolean;
	category: string | null;
};

export type ServiceFullT = {
	id: string;
	name: string;
	slug: string;
	domain: string | null;
	verified: boolean;
	category_id: string | null;
	category: string | null;
	colors: { primary?: string };
	links: Record<string, string>;
	countries: string[];
	ref_link: string | null;
};

export type CategoryT = {
	id: string;
	title: string;
};

export type AppConfigT = {
	logo_base_url: string;
	brandfetch_client_id: string;
	logodev_token: string;
};

export type ApiResponseT<TData> = {
	status: 'success' | 'error';
	data: TData;
	code?: number;
	message?: string;
};

export type FilterT = 'all' | 'verified' | 'unverified' | 'starred';
