// Generated by Opus 4.6 (Anthropic AI)
import { source } from '@/lib/source';
import { llms } from 'fumadocs-core/source';

export const revalidate = false;

export function GET() {
	return new Response(llms(source).index());
}
