// Generated by Claude Opus 4.6
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
	title: 'Soup Admin',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="en">
		<body className="bg-gray-100 text-gray-900 antialiased">{children}</body>
	</html>
);

export default RootLayout;
