// Generated by Claude Opus 4.6

import type { ApiResponseT } from '@/types';

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3000';

export const api = async <TData>(
	path: string,
	token: string,
	options?: { method?: string; body?: unknown },
): Promise<TData> => {
	const method = options?.method ?? 'GET';
	const opts: RequestInit = {
		method,
		headers: {
			Authorization: `Bearer ${token}`,
			'Content-Type': 'application/json',
		},
	};
	if (options?.body !== undefined) {
		opts.body = JSON.stringify(options.body);
	}
	const res = await fetch(`${API_BASE}${path}`, opts);
	if (!res.ok) {
		throw new Error(`${res.status}`);
	}
	const json: ApiResponseT<TData> = await res.json();
	return json.data;
};
