// Generated by Claude Opus 4.6
'use client';

import { useRef, useState } from 'react';

import { countryName, LOCALE_TO_REGION, LOCALES } from '@/lib/constants';
import type { Props } from './service-detail.d';

const ServiceDetail = ({
	service,
	config,
	categories,
	starred,
	onApprove,
	onDelete,
	onSave,
	onStar,
	onSyncLogos,
	onSaveLogo
}: Props) => {
	const [editing, setEditing] = useState(false);
	const [countries, setCountries] = useState<string[]>(service.countries ?? []);
	const [countryDropdownOpen, setCountryDropdownOpen] = useState(false);
	const [color, setColor] = useState(service.colors?.primary ?? '#cccccc');
	const colorInputRef = useRef<HTMLInputElement>(null);

	const nameRef = useRef<HTMLSpanElement>(null);
	const slugRef = useRef<HTMLSpanElement>(null);
	const domainRef = useRef<HTMLSpanElement>(null);
	const refLinkRef = useRef<HTMLSpanElement>(null);
	const categoryRef = useRef<HTMLSelectElement>(null);

	const domain = service.domain ?? '';
	const bfId = config.brandfetch_client_id;
	const ldToken = config.logodev_token;

	const cdnLogo = `${config.logo_base_url}/${service.slug}.webp`;
	const bfLogo = domain ? `https://cdn.brandfetch.io/domain/${domain}/w/1024/h/1024?c=${bfId}` : '';
	const bfSymbol = domain
		? `https://cdn.brandfetch.io/domain/${domain}/w/1024/h/1024/theme/light/symbol?c=${bfId}`
		: '';
	const ldLogo = domain ? `https://img.logo.dev/${domain}?token=${ldToken}&format=webp&size=1024&retina=true` : '';

	const handleSave = () => {
		const cleanDomain = (v: string) =>
			v
				.replace(/^https?:\/\//, '')
				.replace(/\/+$/, '')
				.trim();

		const body: Record<string, unknown> = {
			name: nameRef.current?.textContent?.trim() ?? service.name,
			slug: slugRef.current?.textContent?.trim() ?? service.slug,
			domain: cleanDomain(domainRef.current?.textContent?.trim() ?? domain) || null,
			ref_link: refLinkRef.current?.textContent?.trim() || null,
			colors: { primary: color },
			countries,
			category_id: categoryRef.current?.value || null
		};

		onSave(body);
		setEditing(false);
	};

	const handleCancel = () => {
		setEditing(false);
		setCountries(service.countries ?? []);
		setColor(service.colors?.primary ?? '#cccccc');
	};

	const ce = editing ? true : undefined;

	return (
		<div className={`flex-1 p-6 overflow-y-auto bg-gray-50 ${editing ? 'editing' : ''}`}>
			<div className="max-w-[900px]">
				{/* Actions */}
				<div className="flex gap-2 mb-4">
					<button type="button" onClick={onStar} className="text-lg border-none bg-transparent cursor-pointer">
						{starred ? '\u2605' : '\u2606'}
					</button>
					{!service.verified && (
						<button
							type="button"
							onClick={onApprove}
							className="px-4 py-2 rounded-md text-sm bg-green-600 text-white border-green-600 cursor-pointer"
						>
							&#10003; Approve
						</button>
					)}
					{!editing ? (
						<button
							type="button"
							onClick={() => setEditing(true)}
							className="px-4 py-2 rounded-md text-sm bg-blue-500 text-white border-blue-500 cursor-pointer"
						>
							Edit
						</button>
					) : (
						<>
							<button
								type="button"
								onClick={handleSave}
								className="px-4 py-2 rounded-md text-sm bg-green-600 text-white border-green-600 cursor-pointer"
							>
								Save
							</button>
							<button
								type="button"
								onClick={handleCancel}
								className="px-4 py-2 rounded-md text-sm border border-gray-300 bg-white cursor-pointer"
							>
								Cancel
							</button>
						</>
					)}
					<button
						type="button"
						onClick={onDelete}
						className="px-4 py-2 rounded-md text-sm text-red-600 border border-red-300 bg-white cursor-pointer"
					>
						Delete
					</button>
					{domain && (
						<button
							type="button"
							onClick={onSyncLogos}
							className="px-4 py-2 rounded-md text-sm border border-gray-300 bg-white cursor-pointer"
						>
							Sync logos
						</button>
					)}
				</div>

				{/* Service info */}
				<section className="bg-white border border-gray-200 rounded-xl p-5 mb-4">
					<h3 className="text-[13px] uppercase text-gray-400 tracking-wide mb-3.5">Service</h3>
					<Field label="Name" ref={nameRef} editable={ce} value={service.name} />
					<Field label="Slug" ref={slugRef} editable={ce} value={service.slug} />
					<div className="mb-2.5 flex gap-3 items-center">
						<span className="text-[13px] text-gray-400 w-[90px] shrink-0">Domain</span>
						{editing ? (
							<span
								ref={domainRef}
								contentEditable
								suppressContentEditableWarning
								className="text-[15px] flex-1 px-2 py-1 rounded-md border border-gray-300 bg-white outline-none focus:border-blue-500"
							>
								{domain}
							</span>
						) : (
							<span className="text-[15px] flex-1 px-2 py-1">
								{domain ? (
									<a href={`https://${domain}`} target="_blank" rel="noopener noreferrer" className="text-blue-500">
										{domain}
									</a>
								) : (
									'\u2014'
								)}
							</span>
						)}
					</div>
					<div className="mb-2.5 flex gap-3 items-center">
						<span className="text-[13px] text-gray-400 w-[90px] shrink-0">Category</span>
						{editing ? (
							<select
								ref={categoryRef}
								defaultValue={service.category_id ?? ''}
								className="text-[15px] px-2 py-1 border border-gray-300 rounded-md bg-white"
							>
								<option value="">&mdash; None &mdash;</option>
								{categories.map((c) => (
									<option key={c.id} value={c.id}>
										{c.title}
									</option>
								))}
							</select>
						) : (
							<span className="text-[15px] flex-1 px-2 py-1">{service.category ?? '\u2014'}</span>
						)}
					</div>
					<div className="mb-2.5 flex gap-3 items-center">
						<span className="text-[13px] text-gray-400 w-[90px] shrink-0">Verified</span>
						<span className="text-[15px] px-2 py-1">{service.verified ? '\u2713 Yes' : '\u25CB No'}</span>
					</div>
					<Field label="Ref link" ref={refLinkRef} editable={ce} value={service.ref_link ?? ''} />

					{/* Color */}
					<div className="mb-2.5 flex gap-3 items-center">
						<span className="text-[13px] text-gray-400 w-[90px] shrink-0">Color</span>
						<div className="flex items-center gap-2">
							<button
								type="button"
								className="w-8 h-8 rounded-md border border-gray-300 shrink-0 cursor-pointer"
								style={{ background: color }}
								onClick={() => colorInputRef.current?.click()}
							/>
							<input
								ref={colorInputRef}
								type="color"
								className="invisible absolute w-0 h-0"
								value={color}
								onChange={(e) => setColor(e.target.value)}
							/>
							<span className="text-[15px] px-2 py-1">{color}</span>
						</div>
					</div>

					{/* Countries */}
					<div className="mb-2.5 flex gap-3 items-start">
						<span className="text-[13px] text-gray-400 w-[90px] shrink-0 pt-1">Countries</span>
						<div className="flex flex-wrap gap-1.5">
							{countries.map((code) => {
								const region = LOCALE_TO_REGION[code] ?? code.toUpperCase();
								return (
									<span
										key={code}
										className="inline-flex items-center gap-1 px-2.5 py-1 bg-blue-50 text-blue-500 rounded-full text-xs font-medium"
									>
										{countryName(region)}
										{editing && (
											<button
												type="button"
												className="text-sm leading-none text-gray-400 hover:text-red-600 cursor-pointer"
												onClick={() => setCountries((c) => c.filter((x) => x !== code))}
											>
												&times;
											</button>
										)}
									</span>
								);
							})}
							{editing && (
								<div className="relative inline-block">
									<button
										type="button"
										className="px-2.5 py-1 border border-dashed border-gray-300 rounded-full bg-transparent text-xs text-gray-400 cursor-pointer hover:border-gray-500 hover:text-gray-600"
										onClick={() => setCountryDropdownOpen((o) => !o)}
									>
										+ Add
									</button>
									{countryDropdownOpen && (
										<div className="absolute top-full left-0 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-y-auto z-10 min-w-[180px]">
											{LOCALES.filter((l) => !countries.includes(l)).map((l) => {
												const region = LOCALE_TO_REGION[l] ?? l.toUpperCase();
												return (
													<button
														type="button"
														key={l}
														className="block w-full text-left px-3 py-1.5 text-[13px] hover:bg-gray-100 cursor-pointer"
														onClick={() => {
															setCountries((c) => [...c, l].sort());
															setCountryDropdownOpen(false);
														}}
													>
														{countryName(region)} ({l})
													</button>
												);
											})}
										</div>
									)}
								</div>
							)}
						</div>
					</div>
				</section>

				{/* Logos */}
				<section className="bg-white border border-gray-200 rounded-xl p-5 mb-4">
					<h3 className="text-[13px] uppercase text-gray-400 tracking-wide mb-3.5">Logos</h3>
					<div className="grid grid-cols-[repeat(auto-fill,minmax(180px,1fr))] gap-4">
						<LogoCard label="CDN (current)" src={cdnLogo} />
						{bfLogo ? (
							<>
								<LogoCard label="Brandfetch logo" src={bfLogo} onSave={() => onSaveLogo('bf_logo')} />
								<LogoCard label="Brandfetch symbol" src={bfSymbol} onSave={() => onSaveLogo('bf_symbol')} />
							</>
						) : (
							<div className="text-center p-3 border border-gray-200 rounded-lg bg-white">
								<div className="w-[120px] h-[120px] flex items-center justify-center text-gray-300 text-xs mx-auto border border-dashed border-gray-300 rounded">
									Set domain to see BF logos
								</div>
							</div>
						)}
						{ldLogo && <LogoCard label="logo.dev" src={ldLogo} onSave={() => onSaveLogo('logodev')} />}
					</div>
				</section>
			</div>
		</div>
	);
};

export default ServiceDetail;

type FieldProps = {
	label: string;
	value: string;
	editable?: boolean;
	ref: React.RefObject<HTMLSpanElement | null>;
};

const Field = ({ label, value, editable, ref }: FieldProps) => (
	<div className="mb-2.5 flex gap-3 items-center">
		<span className="text-[13px] text-gray-400 w-[90px] shrink-0">{label}</span>
		<span
			ref={ref}
			contentEditable={editable}
			suppressContentEditableWarning
			className={`text-[15px] flex-1 px-2 py-1 rounded-md border outline-none ${
				editable ? 'border-gray-300 bg-white focus:border-blue-500' : 'border-transparent'
			}`}
		>
			{value}
		</span>
	</div>
);

type LogoCardProps = {
	label: string;
	src: string;
	onSave?: () => void;
};

const LogoCard = ({ label, src, onSave }: LogoCardProps) => {
	const [error, setError] = useState(false);

	return (
		<div className="text-center p-3 border border-gray-200 rounded-lg bg-white">
			<div className="text-[11px] text-gray-400 mb-1.5">{label}</div>
			{!error ? (
				<img
					src={src}
					alt=""
					className="max-w-[120px] max-h-[120px] block mx-auto mb-2 rounded"
					style={{ background: 'repeating-conic-gradient(#f0f0f0 0% 25%, #fff 0% 50%) 50%/16px 16px' }}
					onError={() => setError(true)}
				/>
			) : (
				<div className="w-[120px] h-[120px] flex items-center justify-center text-gray-300 text-xs mx-auto mb-2 border border-dashed border-gray-300 rounded">
					No logo
				</div>
			)}
			{onSave && (
				<button
					type="button"
					onClick={onSave}
					className="text-xs px-3 py-1 border border-gray-300 rounded bg-white cursor-pointer hover:bg-gray-100"
				>
					Save to R2
				</button>
			)}
		</div>
	);
};
