// Generated by Claude Opus 4.6

import type { AppConfigT, CategoryT, ServiceFullT } from '@/types';

export type Props = {
	service: ServiceFullT;
	config: AppConfigT;
	categories: readonly CategoryT[];
	starred: boolean;
	onApprove: () => void;
	onDelete: () => void;
	onSave: (body: Record<string, unknown>) => void;
	onStar: () => void;
	onSyncLogos: () => void;
	onSaveLogo: (type: string) => void;
};
