// Generated by Claude Opus 4.6
'use client';

import type { FilterT } from '@/types';

import type { HeaderProps, SidebarListProps } from './sidebar.d';

const FILTERS: FilterT[] = ['all', 'unverified', 'verified', 'starred'];

export const SidebarList = ({ services, currentIdx, starred, onSelect }: SidebarListProps) => (
	<div className="w-[260px] border-r border-gray-300 overflow-y-auto shrink-0 bg-white">
		{services.map((s, i) => (
			<button
				type="button"
				key={s.id}
				onClick={() => onSelect(i)}
				className={`w-full px-3.5 py-2.5 border-b border-gray-100 text-sm flex justify-between items-center cursor-pointer text-left hover:bg-gray-50 ${
					i === currentIdx ? 'bg-blue-50 border-l-3 border-l-blue-500' : ''
				}`}
			>
				<span className="truncate">
					{starred.has(s.id) ? '\u2605 ' : ''}
					{s.name}
				</span>
				<span className={`text-[11px] shrink-0 ml-2 ${s.verified ? 'text-green-600' : 'text-gray-300'}`}>
					{s.verified ? '\u2713' : '\u25CB'}
				</span>
			</button>
		))}
	</div>
);

export const Header = ({ count, filter, onFilterChange, onExport }: HeaderProps) => (
	<header className="px-6 py-3.5 bg-white border-b border-gray-300 flex justify-between items-center">
		<h1 className="text-lg font-bold">Soup Admin</h1>
		<div className="flex gap-1.5">
			{FILTERS.map((f) => (
				<button
					key={f}
					type="button"
					onClick={() => onFilterChange(f)}
					className={`px-3.5 py-1.5 border rounded-md text-[13px] cursor-pointer ${
						filter === f ? 'bg-gray-900 text-white border-gray-900' : 'bg-white text-gray-500 border-gray-300'
					}`}
				>
					{f.charAt(0).toUpperCase() + f.slice(1)}
				</button>
			))}
		</div>
		<div className="flex items-center gap-3">
			<button
				type="button"
				onClick={onExport}
				className="px-3.5 py-1.5 border border-gray-300 rounded-md bg-white text-gray-500 text-[13px] cursor-pointer"
			>
				Export .sql
			</button>
			<span className="text-[13px] text-gray-400">{count} services</span>
		</div>
	</header>
);
