// Generated by Claude Opus 4.6

import type { FilterT, ServiceListItemT } from '@/types';

export type SidebarListProps = {
	services: readonly ServiceListItemT[];
	currentIdx: number;
	starred: Set<string>;
	onSelect: (idx: number) => void;
};

export type HeaderProps = {
	count: number;
	filter: FilterT;
	onFilterChange: (filter: FilterT) => void;
	onExport: () => void;
};
