// Generated by Claude Opus 4.6

export type ToastStateT = {
	message: string;
	isError: boolean;
	visible: boolean;
	show: (msg: string, error?: boolean) => void;
};

export type Props = {
	message: string;
	isError: boolean;
	visible: boolean;
};
