// Generated by Claude Opus 4.6
'use client';

import type { Props } from './toast.d';

const Toast = ({ message, isError, visible }: Props) => (
	<div
		className={`fixed bottom-18 right-6 px-5 py-2.5 rounded-lg text-sm text-white shadow-lg transition-opacity duration-300 ${
			isError ? 'bg-red-600' : 'bg-green-600'
		} ${visible ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}
	>
		{message}
	</div>
);

export default Toast;
