// Generated by Claude Opus 4.6
'use client';

import { useRef, useState } from 'react';

import type { ToastStateT } from './toast.d';

export const useToast = (): ToastStateT => {
	const [message, setMessage] = useState('');
	const [isError, setIsError] = useState(false);
	const [visible, setVisible] = useState(false);
	const timerRef = useRef<ReturnType<typeof setTimeout>>(null);

	const show = (msg: string, error = false) => {
		if (timerRef.current) clearTimeout(timerRef.current);
		setMessage(msg);
		setIsError(error);
		setVisible(true);
		timerRef.current = setTimeout(() => setVisible(false), 2500);
	};

	return { message, isError, visible, show };
};
