// Generated by Claude Opus 4.6
import type { NextConfig } from 'next';

const securityHeaders = [
	{ key: 'X-Content-Type-Options', value: 'nosniff' },
	{ key: 'X-Frame-Options', value: 'DENY' },
	{ key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
	{ key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
	{ key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=()' },
];

const config: NextConfig = {
	reactStrictMode: true,
	poweredByHeader: false,
	headers: async () => [{ source: '/(.*)', headers: securityHeaders }],
};

export default config;
