// Generated by Claude Opus 4.6
'use client';

import { useEffect, useState } from 'react';
import Login from '@/components/login';
import ServiceDetail from '@/components/service-detail';
import { Header, SidebarList } from '@/components/sidebar';
import Toast, { useToast } from '@/components/toast';
import { api } from '@/lib/api';
import type { AppConfigT, CategoryT, FilterT, ServiceFullT, ServiceListItemT } from '@/types';

const AdminPanel = () => {
	const [token, setToken] = useState('');
	const [loggedIn, setLoggedIn] = useState(false);
	const [config, setConfig] = useState<AppConfigT | null>(null);
	const [categories, setCategories] = useState<CategoryT[]>([]);
	const [services, setServices] = useState<ServiceListItemT[]>([]);
	const [currentIdx, setCurrentIdx] = useState(-1);
	const [currentService, setCurrentService] = useState<ServiceFullT | null>(null);
	const [filter, setFilter] = useState<FilterT>('all');
	const [starred, setStarred] = useState<Set<string>>(new Set());
	const toast = useToast();

	// biome-ignore lint/correctness/useExhaustiveDependencies: runs once on mount
	useEffect(() => {
		const saved = localStorage.getItem('soup_starred');
		if (saved) setStarred(new Set(JSON.parse(saved)));
		const savedToken = sessionStorage.getItem('soup_token');
		if (savedToken) handleLogin(savedToken);
	}, []);

	const saveStarred = (next: Set<string>) => {
		setStarred(next);
		localStorage.setItem('soup_starred', JSON.stringify([...next]));
	};

	const handleLogin = async (t: string) => {
		try {
			const cfg = await api<AppConfigT>('/admin/config', t);
			const cats = await api<CategoryT[]>('/admin/categories', t);
			setToken(t);
			setConfig(cfg);
			setCategories(cats);
			setLoggedIn(true);
			sessionStorage.setItem('soup_token', t);
			await loadList('all', t);
		} catch {
			toast.show('Invalid token', true);
			sessionStorage.removeItem('soup_token');
		}
	};

	const loadList = async (f: FilterT, t?: string) => {
		const tkn = t ?? token;
		setFilter(f);
		let list: ServiceListItemT[];
		if (f === 'starred') {
			const all = await api<ServiceListItemT[]>('/admin/services?filter=all', tkn);
			list = all.filter((s) => starred.has(s.id));
		} else {
			const fetched = await api<ServiceListItemT[]>(`/admin/services?filter=${f}`, tkn);
			list = fetched.filter((s) => !starred.has(s.id));
		}
		setServices(list);
		if (list.length > 0) {
			setCurrentIdx(0);
			const detail = await api<ServiceFullT>(`/admin/services/${list[0]?.id}`, tkn);
			setCurrentService(detail);
		} else {
			setCurrentIdx(-1);
			setCurrentService(null);
		}
	};

	const selectService = async (idx: number) => {
		if (idx < 0 || idx >= services.length) return;
		setCurrentIdx(idx);
		try {
			const svc = services[idx];
			if (!svc) return;
			const detail = await api<ServiceFullT>(`/admin/services/${svc.id}`, token);
			setCurrentService(detail);
		} catch {
			setCurrentService(null);
		}
	};

	useEffect(() => {
		const handler = (e: KeyboardEvent) => {
			if (!loggedIn) return;
			const target = e.target as HTMLElement;
			if (target.isContentEditable || target.tagName === 'INPUT' || target.tagName === 'SELECT') return;

			switch (e.key) {
				case 'j':
				case 'ArrowDown':
					e.preventDefault();
					selectService(currentIdx + 1);
					break;
				case 'k':
				case 'ArrowUp':
					e.preventDefault();
					selectService(currentIdx - 1);
					break;
				case 'a':
					handleApprove();
					break;
				case 'f':
					handleStar();
					break;
				case 'd':
					handleDelete();
					break;
			}
		};
		window.addEventListener('keydown', handler);
		return () => window.removeEventListener('keydown', handler);
	});

	const handleApprove = async () => {
		if (!currentService) return;
		try {
			await api(`/admin/services/${currentService.id}/approve`, token, { method: 'PUT' });
			toast.show('Approved');
			setServices((prev) => prev.map((s, i) => (i === currentIdx ? { ...s, verified: true } : s)));
			setCurrentService((prev) => (prev ? { ...prev, verified: true } : prev));
		} catch (error: unknown) {
			toast.show(`Error: ${error}`, true);
		}
	};

	const handleDelete = async () => {
		if (!currentService || !confirm(`Delete "${currentService.name}"?`)) return;
		try {
			await api(`/admin/services/${currentService.id}`, token, { method: 'DELETE' });
			toast.show('Deleted');
			const next = services.filter((_, i) => i !== currentIdx);
			setServices(next);
			if (next.length > 0) {
				const nextIdx = Math.min(currentIdx, next.length - 1);
				setCurrentIdx(nextIdx);
				const nextSvc = next[nextIdx];
				if (nextSvc) {
					const detail = await api<ServiceFullT>(`/admin/services/${nextSvc.id}`, token);
					setCurrentService(detail);
				}
			} else {
				setCurrentIdx(-1);
				setCurrentService(null);
			}
		} catch (error: unknown) {
			toast.show(`Error: ${error}`, true);
		}
	};

	const handleSave = async (body: Record<string, unknown>) => {
		if (!currentService) return;
		try {
			await api(`/admin/services/${currentService.id}`, token, { method: 'PUT', body });
			const detail = await api<ServiceFullT>(`/admin/services/${currentService.id}`, token);
			setCurrentService(detail);
			setServices((prev) =>
				prev.map((s, i) => (i === currentIdx ? { ...s, name: detail.name, domain: detail.domain } : s)),
			);
			toast.show('Saved');
		} catch (error: unknown) {
			toast.show(`Error: ${error}`, true);
		}
	};

	const handleStar = () => {
		if (!currentService) return;
		const next = new Set(starred);
		if (next.has(currentService.id)) {
			next.delete(currentService.id);
			toast.show('Unstarred');
		} else {
			next.add(currentService.id);
			toast.show('Starred');
		}
		saveStarred(next);
	};

	const handleSyncLogos = async () => {
		if (!currentService) return;
		toast.show('Syncing logos...');
		try {
			await api(`/admin/services/${currentService.id}/sync-logos`, token, { method: 'POST' });
			toast.show('Logos synced');
			const detail = await api<ServiceFullT>(`/admin/services/${currentService.id}`, token);
			setCurrentService(detail);
		} catch (error: unknown) {
			toast.show(`Sync error: ${error}`, true);
		}
	};

	const handleSaveLogo = async (logoType: string) => {
		if (!currentService) return;
		toast.show(`Saving ${logoType}...`);
		try {
			await api(`/admin/services/${currentService.id}/save-logo`, token, {
				method: 'POST',
				body: { logo_type: logoType },
			});
			toast.show(`${logoType} saved to R2`);
		} catch (error: unknown) {
			toast.show(`Error: ${error}`, true);
		}
	};

	const handleExport = async () => {
		try {
			let url = `/admin/export-sql?filter=${filter}`;
			if (filter === 'starred' && starred.size > 0) {
				url = `/admin/export-sql?ids=${[...starred].join(',')}`;
			}
			const sql = await api<string>(url, token);
			const blob = new Blob([sql], { type: 'text/sql;charset=utf-8' });
			const a = document.createElement('a');
			a.href = URL.createObjectURL(blob);
			a.download = `services_${filter}_${new Date().toISOString().slice(0, 10)}.sql`;
			a.click();
			URL.revokeObjectURL(a.href);
			toast.show('SQL exported');
		} catch (error: unknown) {
			toast.show(`Export error: ${error}`, true);
		}
	};

	if (!loggedIn) {
		return (
			<>
				<Login onLogin={handleLogin} />
				<Toast {...toast} />
			</>
		);
	}

	return (
		<div className="flex flex-col h-screen">
			<Header count={services.length} filter={filter} onFilterChange={(f) => loadList(f)} onExport={handleExport} />
			<div className="flex flex-1 overflow-hidden">
				<SidebarList services={services} currentIdx={currentIdx} starred={starred} onSelect={selectService} />
				{currentService && config ? (
					<ServiceDetail
						key={currentService.id}
						service={currentService}
						config={config}
						categories={categories}
						starred={starred.has(currentService.id)}
						onApprove={handleApprove}
						onDelete={handleDelete}
						onSave={handleSave}
						onStar={handleStar}
						onSyncLogos={handleSyncLogos}
						onSaveLogo={handleSaveLogo}
					/>
				) : (
					<div className="flex-1 flex items-center justify-center text-gray-400 text-base">
						{services.length === 0 ? 'No services' : 'Select a service'}
					</div>
				)}
			</div>
			<div className="px-6 py-2.5 bg-white border-t border-gray-300 flex gap-5 text-[13px] text-gray-400 flex-wrap">
				<span>
					<kbd className="bg-gray-100 border border-gray-300 rounded px-1.5 py-0.5 text-gray-600 text-xs">j</kbd>/
					<kbd className="bg-gray-100 border border-gray-300 rounded px-1.5 py-0.5 text-gray-600 text-xs">k</kbd>{' '}
					navigate
				</span>
				<span>
					<kbd className="bg-gray-100 border border-gray-300 rounded px-1.5 py-0.5 text-gray-600 text-xs">a</kbd>{' '}
					approve
				</span>
				<span>
					<kbd className="bg-gray-100 border border-gray-300 rounded px-1.5 py-0.5 text-gray-600 text-xs">f</kbd> star
				</span>
				<span>
					<kbd className="bg-gray-100 border border-gray-300 rounded px-1.5 py-0.5 text-gray-600 text-xs">d</kbd> delete
				</span>
			</div>
			<Toast {...toast} />
		</div>
	);
};

export default AdminPanel;
