// Generated by Claude Opus 4.6
'use client';

import { useState } from 'react';

import type { Props } from './login.d';

const Login = ({ onLogin }: Props) => {
	const [value, setValue] = useState('');

	return (
		<div className="flex items-center justify-center h-screen">
			<div className="text-center">
				<h2 className="text-2xl font-bold mb-4">Soup Admin</h2>
				<input
					type="password"
					className="bg-white border border-gray-300 rounded-lg px-5 py-2.5 text-base w-80"
					placeholder="Admin token"
					// biome-ignore lint/a11y/noAutofocus: login page, expected UX
					autoFocus
					value={value}
					onChange={(e) => setValue(e.target.value)}
					onKeyDown={(e) => {
						if (e.key === 'Enter' && value) onLogin(value);
					}}
				/>
			</div>
		</div>
	);
};

export default Login;
