// Generated by Opus 4.6 (Anthropic AI)
import type { BaseLayoutProps } from 'fumadocs-ui/layouts/shared';

export const gitConfig = {
	user: 'Keireira',
	repo: 'lohikeitto',
	branch: 'master'
};

export const baseOptions = (): BaseLayoutProps => ({
	nav: {
		title: 'Lohikeitto'
	},
	links: [
		{
			text: 'OpenAPI Reference',
			url: '/api-reference'
		}
	],
	githubUrl: `https://github.com/${gitConfig.user}/${gitConfig.repo}`
});
